
# Select economy support (EasyEconomy, EconomyAPI, BedrockEconomy) #
conomy-type: "EasyEconomy"

# Select database type (MYSQL, SQLITE3) #
database-type: "sqlite3"

# MYSQL Settings  #
database-provinder:
 host: 0.0.0.0
 port: 3306
 user: s000_easyplugins
 password: admin
 db: s000_easyplugins
