
# Select database type (mysql, sqlite)
# Select economy support (easyeconomy, economyapi, bedrockeconomy)
def:
 economy_provider: 'EasyEconomy'
 database_provider: 'sqlite'

# MYSQL Settings  #
database-provinder:
 host: 0.0.0.0
 port: 3306
 user: user
 password: admin
 db: your_database
